"""
vani/plugins/builtin/excel_plugin.py

Excel Plugin — Vani creates financial tables, budgets, and trackers.

What it does:
  • Parses spoken/typed financial data from the conversation
  • Creates formatted .xlsx files with headers, totals, conditional formatting
  • Opens the file in Excel / Numbers automatically
  • Supports: budget tables, expense trackers, income statements, EMI tables

Trigger phrases:
  "excel mein banao", "spreadsheet banao", "finance table", "budget table"
  "EMI calculate karo", "expense tracker", "income statement"
"""

from __future__ import annotations
import os
import re
import json
import logging
from datetime import datetime
from pathlib import Path

from vani.plugins.registry import VaniPlugin, PluginResult, PluginContext

logger = logging.getLogger("vani.plugins.excel")


class ExcelPlugin(VaniPlugin):
    name = "excel"
    icon = "📊"
    description = "Creates financial spreadsheets, budget tables, and trackers in Excel."
    category = "finance"
    enabled = False
    triggers = [
        "excel mein banao", "spreadsheet banao", "finance table", "budget table",
        "excel table", "excel file", "xlsx banao", "expense tracker",
        "income statement", "emi calculate", "budget banao", "finance chart",
        "balance sheet", "profit loss", "p&l table", "financial table",
        "salary breakdown", "tax table", "investment tracker",
    ]

    async def on_activate(self, query: str, context: PluginContext) -> PluginResult:
        try:
            import openpyxl
            from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
            from openpyxl.utils import get_column_letter
        except ImportError:
            return PluginResult(
                success=False,
                message="openpyxl install nahi hai. Run: pip install openpyxl"
            )

        # Parse what kind of table is needed
        table_type = self._detect_table_type(query, context)
        data = self._extract_data_from_context(query, context, table_type)

        desktop = Path.home() / "Desktop"
        desktop.mkdir(exist_ok=True)
        now = datetime.now().strftime("%d-%b-%Y_%H%M")
        filename = f"Vani_{table_type.replace(' ', '_')}_{now}.xlsx"
        filepath = desktop / filename

        wb = openpyxl.Workbook()
        ws = wb.active
        ws.title = table_type[:31]

        # ── Styles ────────────────────────────────────────────────────────────
        header_fill   = PatternFill("solid", fgColor="1F3864")
        subhead_fill  = PatternFill("solid", fgColor="2E75B6")
        total_fill    = PatternFill("solid", fgColor="E2EFDA")
        white_font    = Font(bold=True, color="FFFFFF", name="Calibri", size=11)
        header_font   = Font(bold=True, color="FFFFFF", name="Calibri", size=12)
        total_font    = Font(bold=True, name="Calibri", size=11)
        body_font     = Font(name="Calibri", size=10)
        center_align  = Alignment(horizontal="center", vertical="center")
        thin_border   = Border(
            left=Side(style="thin"),  right=Side(style="thin"),
            top=Side(style="thin"),   bottom=Side(style="thin"),
        )

        # ── Title row ─────────────────────────────────────────────────────────
        ws.merge_cells("A1:E1")
        title_cell = ws["A1"]
        title_cell.value = f"📊 {table_type.title()}"
        title_cell.font = Font(bold=True, name="Calibri", size=14, color="FFFFFF")
        title_cell.fill = PatternFill("solid", fgColor="1F3864")
        title_cell.alignment = center_align
        ws.row_dimensions[1].height = 30

        # ── Sub-title ─────────────────────────────────────────────────────────
        ws.merge_cells("A2:E2")
        sub_cell = ws["A2"]
        sub_cell.value = f"Generated by Vani AI  ·  {datetime.now().strftime('%d %B %Y')}"
        sub_cell.font = Font(italic=True, name="Calibri", size=9, color="FFFFFF")
        sub_cell.fill = PatternFill("solid", fgColor="2E75B6")
        sub_cell.alignment = center_align
        ws.row_dimensions[2].height = 18

        # ── Headers ───────────────────────────────────────────────────────────
        headers = data["headers"]
        for col_idx, header in enumerate(headers, 1):
            cell = ws.cell(row=3, column=col_idx, value=header)
            cell.font = header_font
            cell.fill = subhead_fill
            cell.alignment = center_align
            cell.border = thin_border
        ws.row_dimensions[3].height = 22

        # ── Data rows ─────────────────────────────────────────────────────────
        alt_fill = PatternFill("solid", fgColor="F2F2F2")
        for row_idx, row_data in enumerate(data["rows"], 4):
            fill = alt_fill if row_idx % 2 == 0 else None
            for col_idx, value in enumerate(row_data, 1):
                cell = ws.cell(row=row_idx, column=col_idx, value=value)
                cell.font = body_font
                cell.border = thin_border
                if fill:
                    cell.fill = fill
                if col_idx > 1 and isinstance(value, (int, float)):
                    cell.number_format = '₹#,##0.00'
                    cell.alignment = Alignment(horizontal="right")
                else:
                    cell.alignment = Alignment(horizontal="left")

        # ── Totals row ────────────────────────────────────────────────────────
        if data.get("totals"):
            total_row = len(data["rows"]) + 4
            for col_idx, val in enumerate(data["totals"], 1):
                cell = ws.cell(row=total_row, column=col_idx, value=val)
                cell.font = total_font
                cell.fill = total_fill
                cell.border = thin_border
                if col_idx > 1 and isinstance(val, (int, float)):
                    cell.number_format = '₹#,##0.00'
                    cell.alignment = Alignment(horizontal="right")
            ws.row_dimensions[total_row].height = 20

        # ── Column widths ─────────────────────────────────────────────────────
        col_widths = [28, 14, 14, 14, 14]
        for i, width in enumerate(col_widths[:len(headers)], 1):
            ws.column_dimensions[get_column_letter(i)].width = width

        # ── Notes sheet ───────────────────────────────────────────────────────
        ws_notes = wb.create_sheet("Notes")
        ws_notes["A1"] = "💡 Vani Plugin Notes"
        ws_notes["A1"].font = Font(bold=True, size=13)
        ws_notes["A3"] = f"Created: {datetime.now().strftime('%d %B %Y, %I:%M %p')}"
        ws_notes["A4"] = f"Query: {query}"
        ws_notes["A5"] = "This file was auto-generated by Vani AI Plugin System."
        ws_notes.column_dimensions["A"].width = 60

        wb.save(str(filepath))

        # Open in Numbers / Excel
        try:
            import sys, subprocess
            if sys.platform == "darwin":
                subprocess.Popen(["open", str(filepath)])
            elif sys.platform == "win32":
                os.startfile(str(filepath))
        except Exception:
            pass

        return PluginResult(
            success=True,
            message=f"✅ {table_type} Excel file ready! Desktop pe '{filename}' dekho 📊",
            artifact_path=str(filepath),
            artifact_type="xlsx",
            ui_payload={"filename": filename, "table_type": table_type}
        )

    def _detect_table_type(self, query: str, context: PluginContext) -> str:
        q = query.lower()
        if any(x in q for x in ["emi", "loan", "karz"]):
            return "EMI Calculator"
        if any(x in q for x in ["budget", "monthly", "mahina"]):
            return "Monthly Budget"
        if any(x in q for x in ["expense", "kharcha", "spending"]):
            return "Expense Tracker"
        if any(x in q for x in ["salary", "ctc", "income", "aay"]):
            return "Salary Breakdown"
        if any(x in q for x in ["p&l", "profit", "loss", "business"]):
            return "Profit & Loss"
        if any(x in q for x in ["investment", "portfolio", "mutual fund", "sip"]):
            return "Investment Tracker"
        if any(x in q for x in ["tax", "itr", "gst"]):
            return "Tax Summary"
        return "Financial Table"

    def _extract_data_from_context(
        self, query: str, context: PluginContext, table_type: str
    ) -> dict:
        """
        Build table data. Tries to extract numbers from recent conversation,
        falls back to a sensible template.
        """
        # Scan recent messages for numbers
        all_text = " ".join(m.get("content", "") for m in context.recent_messages)
        amounts = re.findall(r'(?:₹|rs\.?|inr)?\s*(\d[\d,]*(?:\.\d{1,2})?)', all_text, re.IGNORECASE)
        amounts = [float(a.replace(",", "")) for a in amounts[:10]]

        TEMPLATES = {
            "Monthly Budget": {
                "headers": ["Category", "Budgeted (₹)", "Actual (₹)", "Difference (₹)", "Status"],
                "rows": [
                    ["Housing / Rent",     25000, 25000,  0,    "✅ On Track"],
                    ["Food & Groceries",   8000,  7500,   500,  "✅ Under"],
                    ["Transport",          3000,  3200,  -200,  "⚠️ Over"],
                    ["Utilities",          2500,  2400,   100,  "✅ Under"],
                    ["Entertainment",      2000,  2800,  -800,  "🔴 Over"],
                    ["Healthcare",         1500,  0,     1500,  "✅ Under"],
                    ["Savings / SIP",      10000, 10000,  0,   "✅ On Track"],
                    ["Miscellaneous",      3000,  2100,   900,  "✅ Under"],
                ],
                "totals": ["TOTAL", 55000, 53000, 2000, ""],
            },
            "Salary Breakdown": {
                "headers": ["Component", "Monthly (₹)", "Annual (₹)", "% of CTC", "Notes"],
                "rows": [
                    ["Basic Salary",       35000,  420000,  40, "40% of CTC"],
                    ["HRA",                17500,  210000,  20, "50% of Basic"],
                    ["Special Allowance",  20000,  240000,  23, "Taxable"],
                    ["PF (Employer)",       4200,   50400,   5, "12% of Basic"],
                    ["Gratuity",            1683,   20196,   2, "4.81% of Basic"],
                    ["Medical Allowance",   1250,   15000,   2, "Tax exempt ₹15k"],
                    ["LTA",                 2917,   35000,   4, "Claimed 2yr cycle"],
                    ["Bonus",               5000,   60000,   7, "Performance based"],
                ],
                "totals": ["GROSS CTC", 87550, 1050596, 100, ""],
            },
            "EMI Calculator": {
                "headers": ["Month", "Opening Balance (₹)", "EMI (₹)", "Principal (₹)", "Interest (₹)"],
                "rows": self._emi_schedule(amounts),
                "totals": [],
            },
            "Expense Tracker": {
                "headers": ["Date", "Category", "Description", "Amount (₹)", "Payment Mode"],
                "rows": [
                    [datetime.now().strftime("%d-%m-%Y"), "Food",       "Lunch",          320,  "UPI"],
                    [datetime.now().strftime("%d-%m-%Y"), "Transport",  "Uber",           180,  "UPI"],
                    [datetime.now().strftime("%d-%m-%Y"), "Shopping",   "Amazon order",  1299,  "Card"],
                    [datetime.now().strftime("%d-%m-%Y"), "Utilities",  "Electricity",   1500,  "Net Banking"],
                ],
                "totals": ["", "", "TOTAL", 3299, ""],
            },
        }

        return TEMPLATES.get(table_type, TEMPLATES["Monthly Budget"])

    def _emi_schedule(self, amounts: list[float]) -> list:
        """Generate first 12 months of an EMI schedule."""
        principal = amounts[0] if amounts else 500000
        rate_annual = amounts[1] / 100 if len(amounts) > 1 and amounts[1] < 30 else 0.085
        rate_monthly = rate_annual / 12
        tenure = 12  # months
        if rate_monthly > 0:
            emi = principal * rate_monthly * (1 + rate_monthly)**tenure / ((1 + rate_monthly)**tenure - 1)
        else:
            emi = principal / tenure
        rows = []
        balance = principal
        for month in range(1, min(13, tenure + 1)):
            interest = balance * rate_monthly
            princ = emi - interest
            balance -= princ
            rows.append([
                f"Month {month:02d}",
                round(balance + princ, 2),
                round(emi, 2),
                round(princ, 2),
                round(interest, 2)
            ])
        return rows
